### ISSUE TITLE
채팅창 아래는 살짝 끊기고 위에 표시줄이 아무리끌어도 안내려와요,,

### ISSUE THREAD

**Issue by aaaddeun** [taewooyo/afreecaTV-plus#10]
![image](https://github.com/taewooyo/afreecaTV-plus/assets/161957291/05e33b06-35c3-40a8-8054-e16455a10331)

**Comment by taewooyo** [comment]
2024.03.03 버전 이후 1.0.21 버전으로 업데이트 부탁드립니다!
