### ISSUE TITLE
채팅 콜렉터에 특정 아이디가 추가되지 않는 이슈

### ISSUE THREAD

**Issue by dovrien** [taewooyo/afreecaTV-plus#11]
특정 아이디만 채팅 콜렉터에 추가가 되지 않습니다.

영상 캡처를 같이 올립니다.

https://github.com/taewooyo/afreecaTV-plus/assets/8412842/2a7129e5-a4f6-416d-be7d-395d0635a345

**Comment by taewooyo** [comment]
@dovrien 안녕하세요. 이슈 알려주셔서 감사합니다.확인해보겠습니다.

홈페이지를 아예 종료 했다가 해도 동일한 현상이 발생할까요?
