### ISSUE TITLE
VOD는 채팅 콜렉터가 안뜹니다.

### ISSUE THREAD

**Issue by Cirlett** [taewooyo/afreecaTV-plus#12]
안녕하세요, 현재 해외 거주 하는 유저중 하나 입니다.

해외라서 그런건지는 모르겠으나, 저는 VOD 는 AFREECATV PLUST 자체가 안되는거 같아서 문의를 드립니다.

설치후 설정은 바꾼것이 없고 라이브 중에는 보이나, VOD에서는 어떤것도 작동하지 않아서 문의를 드립니다.

방송하시는분들 보니까 그분들은 VOD 보시는데도 뜨더라고요.... 이유를 전혀 모르겠습니다. 같은 링크 들어가서 같이보기 또는 클립을 확인 하였으나 둘다 안나오는것은 같더라고요.

밑의 사진이 VOD를 방영시 보이는 화면 입니다.
![image](https://github.com/taewooyo/afreecaTV-plus/assets/22377995/48577555-0c4e-4591-94ff-f3b7f1f14442)

밑의 사진은 라이브 방송을 찍은것 입니다.
![image](https://github.com/taewooyo/afreecaTV-plus/assets/22377995/6e58a114-5704-4a8c-b8a5-b58de088bb93)

**Comment by taewooyo** [comment]
@Cirlett 확인해보고 반영하겠습니다.

**Comment by taewooyo** [comment]
@Cirlett 확인해본 결과 다른 pc와 노트북으로 잘 나타나는데 현재 현상이 아직도 발생하고 있으신가요?

**Comment by Cirlett** [comment]
저는 여전히 안나오는거 같습니다. 

라이브는 항상 잘 나오지만. 

VOD 는 안나옵니다. 가끔 나오기도 하는거 같은데 어떻게 나오는지 모르겠습니다.

확률로는 한 100번에 한번꼴로 나오는거 같은데 뭐가 문제인지 모르겠습니다.

**Comment by spinodal23** [comment]
저의 경우는, 안 뜨는 경우엔 새로고침 계속 하면 결국은 뜨더라구요.
