### ISSUE TITLE
VOD버그

### ISSUE THREAD

**Issue by gibson-kim** [taewooyo/afreecaTV-plus#13]
저만 그런지 모르겠는데 한 3일전부터 VOD에서만 안먹힙니다. 아예 그 창자체가 채팅창에 생성이 안되요.

생방에서는 잘됩니다

**Comment by taewooyo** [comment]
@gibson-kim  vod에 잦은 이슈가 있어서 확인해보고 수정하겠습니다.

**Comment by gibson-kim** [comment]
@taewooyo 원래는 바로 안되더라도 새로고침 2-3번 하면 됐었는데 며칠전부터는 그것도 안되더라구요. 확인해주셔서 감사합니다

**Comment by taewooyo** [comment]
이번 SOOP 개편으로 인해 개선하면서 VOD 수정해서 배포하겠습니다.

**Comment by hamjooo** [comment]
아직 배포 안된 상태인거죠 ? 다시보기유저라 흐흑

**Comment by taewooyo** [comment]
네 빠른 시일 내에 배포하겠습니다.
