### ISSUE TITLE
채팅창 이슈

### ISSUE THREAD

**Issue by YKININ** [taewooyo/afreecaTV-plus#19]
채팅 콜랙터의 크기 수정이 안되는 버그가 있습니다

**Comment by taewooyo** [comment]
SOOP 으로 홈페이지가 개편되면서 수정해서 배포 대기중인상태입니다.

오늘 구글에 검토가 들어간 상태입니다. 빠르면 오늘 새벽 늦으면 내일 오전에 사용가능합니다.

**Comment by shin2221** [comment]
안녕하세요.
혹시 아프리카 때처럼, 다시보기에서도 콜렉터가 기능할 수 있게는 안될까요?
다시보기로 자주봐서 고멤들 채팅을 보고 싶습니다 ㅠㅠ

**Comment by taewooyo** [comment]
네 개발해서 반영시킬 예정입니다. 늦어지만 조금만 기다려주세요~!

**Comment by taewooyo** [comment]
다시보기 콜렉터는 오늘 검토에 들어가서 구글에서 승인해주면 사용가능합니다.

**Comment by taewooyo** [comment]
@shin2221 배포완료되었습니다.
