### ISSUE TITLE
채팅창 상하 변경 버튼 Tooltip z-index 

### ISSUE THREAD

**Issue by seoseonyu** [taewooyo/afreecaTV-plus#20]
`채팅창 상하 변경` 버튼 Tooltip z-index

![image](https://github.com/user-attachments/assets/21b0f108-d131-471a-acc1-915a3a197b07)

contribute 하려고 햇는데 soop 대응 수정사항이 아직 안 올라온듯하여 이슈등록 합니다.

**Comment by taewooyo** [comment]
contribute 환영입니다. 제가 최신 버전으로 업데이트해놓을게요!

**Comment by seoseonyu** [comment]
@taewooyo  혹시 최신 버전 언제 Push 예정이신가요?

**Comment by taewooyo** [comment]
@seoseonyu 방금 푸시 완료된 상태입니다. 감사합니다.
