### ISSUE TITLE
채팅 콜렉터 버그

### ISSUE THREAD

**Issue by moose6651** [taewooyo/afreecaTV-plus#22]
콜렉터가 채팅위에 쥐꼬리만큼 보입니다. 상하 반전해도 밑에 쥐꼬리만큼 나옵니다. 해결하는 방법이 있나요??

**Comment by taewooyo** [comment]
구분자를 드래그해서 사이즈 조절이 가능합니다!
혹시 이부분을 해결이 안된다면 캡처로 올려주시면 빠른 대응 진행할게요!

**Comment by moose6651** [comment]
구분자를 드래그해도 사이즈 조절이 안됩니다 ㅠㅠ.
![스크린샷 2024-10-15 143802](https://github.com/user-attachments/assets/813c781c-e316-4178-90bf-b47624a3e76c)

**Comment by taewooyo** [comment]
제보 감사합니다. 빠른 수정 해보겠습니다.
