### ISSUE TITLE
스타일 수정

### ISSUE THREAD

**Issue by seoseonyu** [taewooyo/afreecaTV-plus#25]
- 아이콘 배경으로 인해 아이콘이 이상하게 표시되는 현상

![image](https://github.com/user-attachments/assets/b1531643-4e88-43af-9947-646d859e1056)

- 확장프로그램 내 상단 로고 수정

![image](https://github.com/user-attachments/assets/1d25c45a-2933-4696-95f4-90636285faf4)

**Comment by seoseonyu** [comment]
@taewooyo 

아이콘 견본인데 혹시 마음에 드시는게 있으실까요

![image](https://github.com/user-attachments/assets/63a395d8-985d-4725-806c-5b68e2b4c6f6)

**Comment by seoseonyu** [comment]
확장프로그램 상단 로고 예시인데 위에서부터 1~4 번입니다.

마음에 드시는게 있으실까요?

![image](https://github.com/user-attachments/assets/e262179e-3395-40cf-a4df-0434ed5fa2d0)

**Comment by taewooyo** [comment]
와. 디자인이 무지했었는데 정말감사합니다.반영하고싶어요

**Comment by taewooyo** [comment]
와. 디자인이 무지했었는데 정말감사합니다.반영하고싶어요.

아이콘은 1478 이쁜것같네요.

확장프로그램 상단은 4번이 먼가 재밌어 보이기도하네요.

**Comment by taewooyo** [comment]
공유받을수 있을까요?

**Comment by seoseonyu** [comment]
혹시 상단 4번이 위에서 4번째  일까요?

**Comment by taewooyo** [comment]
네 위에서 4번째입니다.
1번도 괜찮아보이고요 ㅋㅋ

**Comment by seoseonyu** [comment]
메일 남겨주시면 오늘 저녁 쯤 이메일로 

아이콘 1, 4, 7, 8 
상당 1, 4

전달 드리겠습니다 :)

만약 PR 원하시면 제가 적용해서 PR 올리겠습니다. 
편하게 말해주세요 👍

**Comment by taewooyo** [comment]
Pr올리셔도 좋고 전달주셔도 좋아요.
메일 : skaxodn97@gmail.com 

원하시는 방향으로 진행해주세요
