### ISSUE TITLE
다시보기 콜렉터 아직인가요 ㅠ

### ISSUE THREAD

**Issue by hamjooo** [taewooyo/afreecaTV-plus#26]
ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ

**Comment by taewooyo** [comment]
빠른시일내 배포하겠습니다. 조금만 기다려주세요.

**Comment by hamjooo** [comment]
다시보기 콜렉터 감사합니다 !!! 드디어 흐흑

**Comment by taewooyo** [comment]
현재 개발중이라 최대한 반영해볼게요!

**Comment by taewooyo** [comment]
오늘 검수로 들어갔습니다. 검수 완료되면 배포될 예정이니 다시보기 콜렉터 사용하시면 됩니다.

**Comment by taewooyo** [comment]
@hamjooo 배포완료되었습니다.

**Comment by hamjooo** [comment]
감사합니다 고생하셨슴닷 !!
