### ISSUE TITLE
설정 저장 및 불러오기 구현

### ISSUE THREAD

**Issue by seoseonyu** [taewooyo/afreecaTV-plus#28]
- 구현 후 PR 예정

**Comment by seoseonyu** [comment]
혹시 업데이트 안되더라도 개발중이신 최신 사항들 push 주기적으로 가능할까요?... :)

**Comment by taewooyo** [comment]
네. 개발중인 기능도 푸시해놓겠습니다.
현재 본업 때문에 개발을 못하고 있는 상태라 우선순위는 다시보기 필터링 기능이 될 것입니다.

설정 저장 및 불러오기 구현 컨트리뷰트하실 예정이면 진행해주셔도 됩니다~

**Comment by taewooyo** [comment]
@seoseonyu 
혹시 해당 이슈 개발 중에 있으실까요?

**Comment by seoseonyu** [comment]
아직 시작 안했습니다 구상만 해둔 상태입니다

**Comment by taewooyo** [comment]
구상방법이 어떠한 방식인지 알 수 있을까요? 개발 하실 예정이라면 저는 다른 작업을 진행해보려합니다.

**Comment by seoseonyu** [comment]
단순하게 localStorage 저장 값을 json으로 import/export 할 수 있게 할 예정입니다.

**Comment by taewooyo** [comment]
@seoseonyu 잘작동하는 것 같습니다.
설정불러오기 저장에 사용자가보기에 어렵긴한데, 이부분은 어쩔수 없는거겟죠?

**Comment by seoseonyu** [comment]
흠... 우선 별도 서버나 그런거 필요 없도록 설정파일 다운로드로 하긴했는데

별도 서버를 두지않는이상 다른 방법이 안떠오르네요

별도 가이드를 둬야하려나요...

**Comment by taewooyo** [comment]
아하 text로 분리해서 그냥 json 파일에 찾아서 강제로넣는 방법으로 한번 제가해볼게요!
우선 잘작동해서 머지할게요!
