### ISSUE TITLE
채팅 콜렉터

### ISSUE THREAD

**Issue by ksso8** [taewooyo/afreecaTV-plus#29]
다시보기 채팅 콜렉터가 된다고해서 보려고했는데 콜렉터 채팅창이 위아래로 크기 조절이 안되더라구요.
그리고 다시보기 채팅 콜렉터 위아래 크키 조절하려고 왔다갔다해도 안돼서 실시간 방송 보려고 사이트창 바꿨는데 실시간 방송 채팅 콜렉터도 크기가 커져있거나 작아져 있는 현상이 있었습니다. ( 이 현상 때문에 제거했다가 다시 다운로드 해봤지만 그대로였습니다. )

고칠 수 있는 버그라면 고쳐주시면 감사하겠습니다!

**Comment by taewooyo** [comment]
현재 다시보기 채팅 콜렉터는 개발중이라 안되는게 맞아요! 버그 수정해서 빠르게 배포할게요!
오늘 다시보기 완료해서 최대한 배포해볼게요.

**Comment by taewooyo** [comment]
@ksso8  배포 완료되었습니다.
