### ISSUE TITLE
확장프로그램 UI 재구성

### ISSUE THREAD

**Issue by seoseonyu** [taewooyo/afreecaTV-plus#33]
설정 불러오기 버튼 넣을 위치 정하다가.

도저히 넣을 자리가 감이 안잡혀서 자리 만들어볼겸

UI 완전 재구성 해보고있습니다.

UI 재구성 의사가 있으신가요?

![image](https://github.com/user-attachments/assets/7fb625b0-1524-411c-a011-ae204fc0ba4e)
![image](https://github.com/user-attachments/assets/b842c49d-55e8-4a73-8e72-13c79b6c5b8c)

**Comment by taewooyo** [comment]
네 가능헙니다. 현재 pr로 들어온 컴포넌트 분리 작업이 있어서 이부분 머지하고서 반영은 어떠하신가요?

**Comment by taewooyo** [comment]
이부분에서 닉네임등록과 아이디등록도 잔영이되어야합니다.

**Comment by seoseonyu** [comment]
네 :)

닉네임 등록, 아이디 등록 작업 진행중 입니다.

UI 코드 완전 재작성 수준이라 작업완료시
**컴포넌트 분리 작업**이 반영된 코드 기준으로 옮기는 작업 예정입니다!

작업 완료후 모든기능 on/off 처리 테스트 진행 예정입니다.

추후 PR 요청 시 기능 누락 여부 검토 요청 드리겠습니다!

**Comment by seoseonyu** [comment]
@taewooyo 혹시 #31 건은 병합 예정일이 어떻게 될까요?

필터리스트 추가하였습니다.
(최대한 깔끔하게 넣어보고 싶었는데 제 머리는 여기까지가 한계네요ㅎㅎ...)

## Full
![image](https://github.com/user-attachments/assets/9ef0555e-61c5-424a-bfa3-8163ac47b577)

## 필터리스트 Close

아코디언 형식으로 접을 수 있게 하였습니다.

![image](https://github.com/user-attachments/assets/fe24bbd0-2bb2-427e-a4bd-749874be0b4c)

**Comment by taewooyo** [comment]
@seoseonyu 좋은 PR 감사합니다.
제가 회사일로 인해 주말 중에 머지 진행하려고해요! 감사합니다.

**Comment by seoseonyu** [comment]
고생많으십니다 해당건 머지 되면 작업 진행하겠습니다 :)

**Comment by taewooyo** [comment]
@seoseonyu 확인 후 머지 완료되었습니다. 작업 진행하셔도 될것같아요!
