### ISSUE TITLE
다시보기 채팅 구분자가 안켜집니다.

### ISSUE THREAD

**Issue by moose6651** [taewooyo/afreecaTV-plus#34]
![image](https://github.com/user-attachments/assets/59add29b-6c38-4c7a-9bab-7124af8e24d1)
![image](https://github.com/user-attachments/assets/96a0b4e6-000e-49ab-9e55-33a288cd5e2f)
1. 다시보기 채팅 구분자가 안켜집니다.
2. 생방송의 구분자가 박혀서 안나옵니다. 아무리 드래그해도 저럽니다 ㅠㅠ.
제가 해외에 살아서 저러는건가요? 다른 분들은 다 잘 사용하시던뎅...

**Comment by taewooyo** [comment]
이슈 제보 감사합니다. 확인하고 공유드릴게요!

**Comment by taewooyo** [comment]
@moose6651 혹시 확장프로그램이 다른거랑 충돌이 났을 수도 있을 것 같아보이긴합니다.

정확한 증상이

다시보기에서 : 가 안나타나는 것과 2번째는 상세한 설명을 부탁드려도 될까요?

**Comment by moose6651** [comment]
첫 번째 사진: 다시 보기에서 채팅 콜렉터가 안 켜집니다. 매니저나 열혈들의 채팅을 구분해주는 창이욥.

두 번째 사진: 생방송 중에 매니저, 열혈 등의 채팅을 따로 보개해주는 창이 채팅창 상단에 박혀서 안 나옵니다 (드래그 등등 온갖 걸 다해봤습니다.) 다른 스트리머들을 잘 되던데 제가 문제일까요? 이 현상은 몇달전부터 그랬습니다. 몇달전에는 다른 확장프로그램들이 없었습니다. 그래서 충돌은 아닌 것 같습니다. 혹시 해결하기 힘드시면 무리하지 마세요 ㅠㅠ.

**Comment by moose6651** [comment]
앗 해결됬어요!!... 정말 죄성합니다. 확장프로그램 싹 다 지우고 다시 다운로드 받으니 작동해여!
그런데 다시보기 채팅 콜렉터가 작동이 안됩니다.

**Comment by taewooyo** [comment]
@moose6651  라이브부분이 잘작동해서 다행이네요. 다시보기 채팅콜렉터도 잘작동해야 맞는데,
혹시 마지막으로 재설치진행해주실 수 있나요. 개발에서도 확인해보겠습니다.

**Comment by moose6651** [comment]
재설치했는데 계속 안되네요....

**Comment by taewooyo** [comment]
말씀하시는 구분자가 채팅콜렉터 중간 나뉘는 선을 말씀하시는 걸까요?
채팅의 : 의구분자를 말씀하시는걸가요?

**Comment by moose6651** [comment]
채팅콜렉터 중간 나뉘는 선을 말하는겁니다. 제가 이상하게 말씀드렸네요.

**Comment by taewooyo** [comment]
@moose6651 새롭게 배포가 나갔었는데 업데이트 후에 현재도 그러한 현상이 발생중일까요?

**Comment by moose6651** [comment]
확장프로그램 충돌 가능성이 있어서 모든 확장프로그램의 삭제와 동시에 재설치를 했습니다. 아직도 안됩니다ㅠㅠ. 다른 사람들의 버그제보를 보고 있는데 저 처럼 해외거주자이신 분이 다시보기의 채팅콜렉터가 작동 안된다는 말이 있더라구요. 해외거주자들에게 이러한 문제가 발생하는 것 같습니다.
![스크린샷 2024-11-10 212914](https://github.com/user-attachments/assets/7574e410-ce74-4135-a457-af32ddf2e733)

**Comment by taewooyo** [comment]
@moose6651 해결 완료되면 다시 한번 멘션드릴게요!
