### ISSUE TITLE
저장기능에 대한 질문 입니다.

### ISSUE THREAD

**Issue by seoseonyu** [taewooyo/afreecaTV-plus#36]
안녕하세요, 고생 많으십니다. 

다름이 아니라 설정 저장,불러오기 수정 사항 하였는데 궁금증이 있어 이슈 생성 하였습니다.

기존(localStorage 전체 저장)에 스위치 설정 항목 까지 모두 백업하고 있었습니다.

변경 이후 필터링 리스트만 있는 것으로 보이는데 위에 스위치 옵션들의 설정 저장은 필요 없을까요?

만약 필터 목록 저장으로 현행 유지 하게 된다면 설정 저장, 불러오기 버튼이 필터 리스트 쪽으로 옮겨져야 할 것 같습니다.

가장 위에 있는 상태여서 전체 설정을 저장 하고 불러오는 것 처럼 보이게 되서 그렇습니다.

**Comment by taewooyo** [comment]
네 그렇네요 이부분 수장해서 새롭게 업데이트 해야할 것 같아요!!

**Comment by seoseonyu** [comment]
필터링리스트만 저장 유지하시고 버튼아래로 내리실건가요?

![image](https://github.com/user-attachments/assets/de244a7c-3150-4fa2-bca0-3fd941574170)
이 부분 조정이 필요해 보여서 

방향 말해주시면 포함하여 수정해서 PR 하겠습니다.

**Comment by taewooyo** [comment]
@seoseonyu 사용자가 다른 스위치옵션은 직접하는게 맞을 것 같아요.
버튼문구를 바꾸거나 문구 수정하거나아래로 내려도될 것 같아요.

편하신대로 변경해보셔도 됩니다.
