### ISSUE TITLE
더 이상 채팅 콜렉터 기능이 동작하지 않음.

### ISSUE THREAD

**Issue by 6oRim** [taewooyo/afreecaTV-plus#5]
최근 아프리카TV 채팅 시스템 변화로 인해 채팅 콜렉터 기능이 동작하지 않게 됨.
수정 요청합니다

**Comment by taewooyo** [comment]
@GreenJJR 최신 업데이트가 완료 되었습니다.
최신 업데이트 내용으로 콜렉터 기능이 작동합니다.

확인 후 작동하지 않으면 mention 부탁드립니다.

**Comment by 6oRim** [comment]
> @GreenJJR 최신 업데이트가 완료 되었습니다. 최신 업데이트 내용으로 콜렉터 기능이 작동합니다.
> 
> 확인 후 작동하지 않으면 mention 부탁드립니다.

확인 했습니다 감사합니다!
