### ISSUE TITLE
매니저 등장 시 채팅창 얼음

### ISSUE THREAD

**Issue by Oakmura** [taewooyo/afreecaTV-plus#6]
안녕하세요, 윈도우 11 쓰고  크롬쓰고 있습니다. 채팅방에 매니저가 등장하면 채팅창이 자동으로 내려가지 않고, '매니저가 등장했습니다' 라는 문구에서 멈춰서 내려가지 않습니다.

**Comment by Oakmura** [comment]
![image](https://github.com/taewooyo/afreecaTV-plus/assets/89961585/147ff86c-97cc-4d5b-95ce-a381fa8c8161)
이런식으로 매니저가 등장한 시점부터 자동으로 스크롤이 내려가지지 않습니다.

**Comment by taewooyo** [comment]
@Oakmura 안녕하세요.
심사 들어가서 오늘 오후에 배포되면 이 현상이 나타나지 않을 것입니다.

**Comment by Oakmura** [comment]
감사합니다 ~
