### ISSUE TITLE
전체화면 버그

### ISSUE THREAD

**Issue by dhou7015** [taewooyo/afreecaTV-plus#9]
전체화면동안 댓글이 달려도 채팅 콜렉터에 안뜨는 버그가 있습니다

**Comment by taewooyo** [comment]
@dhou7015 안녕하세요.
전체화면 후 채팅을 끄고 다시키면 다른 사람들이 치는 채팅이 콜렉터에 안나타난다는 의미일까요?

현재 아프리카 자체에서 채팅을 끈면 채팅에 데이터가 안들어오게 만들어놓은 것 같아요. 기존에는 계속해서 데이터가 쌓이는 형태였는데 과부하 관련으로 변경되었나봐요. 혹시 이부분이 문제셨다면 아프리카 자체에서 수정해줘야할 것 같아요.

추가로, 이부분이 이슈가 아니라면 어떤 문제인지 이미지라도 캡쳐해서 여기에 올려주실 수 있을까요?

감사합니다.
